<?php
return array(
    'dictScrollTitleValue'=>'Scroll to the top of the page',
    'dictMenuToggle'=>'Menu toggle',
    'dictToggle'=>'toggle',
    'dictNavDetails'=>'Details',
    'dictNavLanguage'=>'Language',
    'dictNoticeIE'=>'Our site does not support versions of Internet Explorer older than IE9. We apologize for the inconvenience.',
    'dictNoticeEUcookie1'=>'Cookie Notice (for EU compliance)',
    'dictNoticeEUcookie2'=>'We use Google analytics to understand how people find and use our site. To enable us to anonymously collect information on how our site is being used, please <span class="d-none d-sm-inline">click or </span>press the <span class="underline-green">Accept button</span>. <span class="d-none d-sm-inline">That authorizes us to: place a cookie on your device to remember your choice; to instruct your browser to send information (including your IP address) to Google; and for Google to place cookies related to our site on your browser.</span>',
    'dictNoticeEUcookie3'=>'To decline<span class="d-none d-sm-inline"> the use of cookies and Google services</span>, <span class="d-none d-sm-inline">click or </span>press the <span class="underline-red">Opt-out button</span>.',
    'dictNoticeEUcookie4a'=>'For more information<span class="d-none d-sm-inline"> on our use of cookies</span>, please review our ',
    'dictNoticeEUcookie4b'=>'Site Terms of Use / Privacy Policy',
    'dictNoticeEUcookie4c'=>'Privacy policy',
    'dictNoticeEUcookie4d'=>'.',
    'dictNoticeEUcookie5a'=>'Accept tracking cookies',
    'dictNoticeEUcookie5b'=>'Accept',
    'dictNoticeEUcookie6a'=>'Opt out of tracking cookies',
    'dictNoticeEUcookie6b'=>'Opt-out',
    'dictNoticeSkipLink'=>'Skip to main content',
    'dictLogoAltText' =>'Site Construction – Logo is a safety helmet – link to the home page',
    'dictFooterHeading1'=>'About this site',
    'dictFooterContent1'=>'This site is an experiment in creating a dynamic website using Fat-Free &amp; Bootstrap 5. The files are available on <a href="https://github.com/RichDeBourke/simple-f3-multi-lang-site" title="GitHub repository with the Fat-Free Framework and Bootstrap files">GitHub</a> and most of the logic for the site is documented within. A similar website built with Fat-Free &amp; Bootstrap 4 is at <a href="http://sbf-testing.byethost7.com/en/home" title="Previous test site build with Bootstrap 4">http://sbf-testing.&#8203;byethost7.&#8203;com/&#8203;en/home</a>.',
    'dictFooterHeading2'=>'About me',
    'dictFooterContent2'=>'I help Korean businesses with their English com&shy;mu&shy;ni&shy;cation (presen&shy;tations, web content, and emails) and web design.',
    'dictFooterHeading3'=>'Contact',
    'dictFooterContent3a'=>'If you have questions about this site or if you need help with business in Korea, you can contact me at: ',
    'dictFooterContent3b'=>'',
    'dictFooterContent3c'=>'Contact SBF Consulting via email',
    'dictFooterTerms'=>'Terms of Use | Privacy Policy',
    'dictFooterTermsTitle'=>'Terms of Use for this site including privacy',
    'dictFooterCopyrightTitle'=>'The website for my consulting business in Korea',
    'dict404PageTitle'=>'404 - Page not found error',
    'dict404PageDescription'=>'Page not found error',
    'dict404NotFoundHeader'=>'Page Not Found — A 404 Error',
    'dict404PageURL'=>'There is no page at: <strong>{0}</strong>',
    'dict404Notice1'=>'This may be because:',
    'dict404Notice2'=>'The page you are looking for is no longer available,',
    'dict404Notice3'=>'or you clicked a link from another site that has an error,',
    'dict404Notice4'=>'or the portion you typed, <strong>{0},</strong> has an error.',
    'dict404Notice5'=>'Please try the links above, or contact us for assistance.',
    'dict404Looked'=>'We looked, but we can&rsquo;t find the page you requested',
    'dict500PageTitle'=>'5XX - Server error',
    'dict500PageDescription'=>'There is a problem with our server',
    'dict500ServerErrorHeader'=>'We&rsquo;re tackling a {0} error',
    'dict500Notice1'=>'There&rsquo;s something wrong with our server (there&rsquo;s nothing wrong on your side).',
    'dict500Notice2'=>'As you can see, we&rsquo;re going through our code (<em>not really &ndash; it&rsquo;s just an animation, but hopefully we do know about the problem and we are working to resolve it</em>).',
    'dict500Notice3'=>'Here are a few things you can try that may resolve the problem:',
    'dict500Notice4'=>'<strong>Refresh the page</strong> (sometimes this helps)',
    'dict500Notice5'=>'<strong>Try again</strong> in 30 minutes',
    'dict500Notice6'=>'<strong>Email us</strong> and let us know what&rsquo;s happening',
    'dict500Notice7'=>'We apologize for the inconvenience.',
    'dictContactPageTitle'=>'Contact Us',
    'dictContactPageDescription'=>'You can contact us by via a contact form or by email',
    'dictContact01'=>'Contact us',
    'dictContact02'=>'Contact information',
    'dictContact03'=>'Your name',
    'dictContact04'=>'Name',
    'dictContact05'=>'Your email',
    'dictContact06'=>'email@example.com',
    'dictContact07'=>'Your subject',
    'dictContact08'=>'Subject',
    'dictContact09'=>'Your message',
    'dictContact10'=>'Message',
    'dictContact11'=>'Submit',
    'dictContact12'=>'Required',
    'dictContact13'=>'Thank you for contacting us. We will respond as soon as we can.',
    'dictContact14'=>'Our server is not able to process your email address as entered.',
    'dictContact15'=>'We experienced an unknown problem with submitting your message. Please send your request using our email address below.',
    'dictTermsPageTitle'=>'Terms of Use | Privacy Policy',
    'dictTermsPageDescription'=>'Conditions for using this site and information about collecting personal information',
    'dictTermsOptOutQuestion'=>'Please confirm you do not want to use Google services.'
);
